/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package webview.jvm.console

import kotlin.test.Test
import kotlin.test.assertTrue

class WebViewConsoleTest {
    @Test fun someLibraryMethodReturnsTrue() {
        val classUnderTest = Library()
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
    }
}
